Re former
Leon-Mbegera/re-former pull request #1
Opened 2021-06-09 14:51 UTC by Leon-Mbegera

This project showcases ways of building a form using both the old fashion way and the new way.

2021-06-09 20:05 UTC, umararshadbut requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Leon-Mbegera 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] When we edit and submit, the edit is working. But it is not redirecting properly. I'm commenting that where is issue. Please fix it.


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

2021-06-09 20:05 UTC, umararshadbut commented on app/controllers/users_controller.rb
> +      redirect_to @user
`redirect_to edit_user_path(<USER_ID`>) if the user was saved (remember to change <USER_ID> to the code that works for the student implementation)

2021-06-10 07:55 UTC, Leon-Mbegera commented
I've addressed all required changes:
- redirecting the user update to edit page
- Created a show view

2021-06-10 08:39 UTC, umararshadbut approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Leon-Mbegera ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**Umair**

2021-06-10 09:12 UTC, merged